- name: Deploy React to GitHub Pages
  uses: bitovi/github-actions-react-to-github-pages@v1.2.3
  with:
    checkout: 'true'
    path: build
    install_command: npm install
    build_command: npm run build
    caching: 'true'
