name: Deploy React to GitHub Pages
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.3
        with:
          path: build
